### ISSUE TITLE
McDonalds fries

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/Recipes#46]
## Ingredients
- 4-5 large Maris Piper potatoes
- Salt

## Method
1. Peel the potatoes and then remove any bad bits.
2. Carefully chip the potatoes using a mandoline slicer.
3. Place the fries in a bowl and run cold water through the bowl to remove the starch.
4. Parboil the fries in a pan of cold water being careful to not overcook the potato at this stage.
5. Remove from the boil and drain in a colander.
6. Once drained place colander over the pan and place on low heat for a few minutes to dry the potatoes.
7. Fry the potatoes at low heat for 3-4 minutes.
8. Drain and allow to cool in the fridge or place in the freezer.
9. Once ready remove them and sprinkle some sea salt over the potato.
10. Finish by frying for a final time for 2-3 minutes or until golden.

**Comment by jcallaghan** [comment]
https://www.seriouseats.com/perfect-french-fries-recipe

**Comment by jcallaghan** [comment]
![image](https://user-images.githubusercontent.com/7449908/127862653-88c9f157-5358-4955-b3c3-df2397ebc6fa.png)

aht.seriouseats.com/2010/05/the-burger-lab-how-to-make-perfect-mcdonalds-style-french-fries.html

**Comment by jcallaghan** [comment]
https://www.youtube.com/watch?v=y5KPZp2t52U

**Comment by jcallaghan** [comment]
https://www.mashed.com/68896/make-perfect-mcdonalds-fries-recipe/

**Comment by jcallaghan** [comment]
https://www.seriouseats.com/the-burger-lab-how-to-make-perfect-mcdonalds-style-french-fries

**Comment by jcallaghan** [comment]
https://www.seriouseats.com/perfect-french-fries-recipe

**Comment by bryanbr23** [comment]
I will have to try some of these techniques.

~Bryan
________________________________
